package fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-20T13:39:53.134+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "ITeamForceService", 
                  wsdlLocation = "http://localhost:8081/services/teamforce?wsdl",
                  targetNamespace = "http://service.teamforce.soa.mehdi.polytech.fr/") 
public class ITeamForceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.teamforce.soa.mehdi.polytech.fr/", "ITeamForceService");
    public final static QName TeamforcePort = new QName("http://service.teamforce.soa.mehdi.polytech.fr/", "teamforcePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/services/teamforce?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ITeamForceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/services/teamforce?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ITeamForceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ITeamForceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITeamForceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITeamForceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITeamForceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ITeamForceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Teamforce
     */
    @WebEndpoint(name = "teamforcePort")
    public Teamforce getTeamforcePort() {
        return super.getPort(TeamforcePort, Teamforce.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Teamforce
     */
    @WebEndpoint(name = "teamforcePort")
    public Teamforce getTeamforcePort(WebServiceFeature... features) {
        return super.getPort(TeamforcePort, Teamforce.class, features);
    }

}
