package fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-20T13:39:53.128+02:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://service.teamforce.soa.mehdi.polytech.fr/", name = "teamforce")
@XmlSeeAlso({ObjectFactory.class})
public interface Teamforce {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addCustomer", targetNamespace = "http://service.teamforce.soa.mehdi.polytech.fr/", className = "fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.AddCustomer")
    @WebMethod
    @ResponseWrapper(localName = "addCustomerResponse", targetNamespace = "http://service.teamforce.soa.mehdi.polytech.fr/", className = "fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.AddCustomerResponse")
    public fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.CustomerResponse addCustomer(
        @WebParam(name = "Customer", targetNamespace = "")
        fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.CustomerRequest customer
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://service.teamforce.soa.mehdi.polytech.fr/", className = "fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.AddOrder")
    @WebMethod
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://service.teamforce.soa.mehdi.polytech.fr/", className = "fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.AddOrderResponse")
    public fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.OrderResponse addOrder(
        @WebParam(name = "new_order", targetNamespace = "")
        fr.polytech.soakillers.soa.misterGoodDeal.teamForceClient.OrderRequest newOrder
    );
}
